# ── Subtitles ─────────────────────────────

sub-font="Ravi"
sub-font-size=28

sub-color="#FFFFFF"

sub-border-color="#000000"
sub-border-size=0.6

sub-shadow-color="#000000"
sub-shadow-offset=0

sub-margin-y=120

sub-bold=yes
sub-italic=no

# Force the same style even for ASS/SSA subtitles
sub-ass-override=force


# ── ModernZ ───────────────────────────────

# Disable mpv's default OSC
osc=no

# Hide mpv's seek/OSD overlay when seeking
osd-level=0
